<?php

namespace App\Model;

use App\Job;
use Carbon\Carbon;

class Operative extends Job
{

    public function __construct(array $attribute = array())
    {

        parent::__construct($attribute);

        $this->setRawAttributes(array_merge($this->attributes, array(
            'OS' => 'NOT DECLARED',
            'startTime' =>Carbon::now()->addMinutes(2),
            )
        ), true);

    }



    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope('operative', function (Builder $builder) {
            $builder->where('type', 'operative');
        });

        static::creating(function ($article) {
            $article->type = 'operative';
        });
    }

    public function toJson($options = 0)
    {
        return parent::toJson($options); // TODO: Change the autogenerated stub
    }


}
